language: python
python:

  - "2.7"


# command to install dependencies
install:
  - pip install -r requirements.txt
  
before_script:
  - pip uninstall numpy -y
  - pip install -I numpy==1.11.3
# command to run tests
script: python testPython.py
